apiVersion: v1
kind: Namespace
metadata:
  name: grpc-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grpc-server
  name: grpc-server
  namespace: grpc-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grpc-server
  strategy: {}
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
      - image: docker.io/vimuchiaroni/grpc-server:0.1
        name: grpc-server
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grpc-server
  annotations:
    service.cilium.io/lb-l7: enabled
  name: grpc-server
  namespace: grpc-server
spec:
  type: ClusterIP
  ports:
  - port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: grpc-server